backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: ../../static/img

site_url: https://affectionate-ride-be4308.netlify.app/

collections:
  - name: 'library'
    label: 'Bibliothek'
    folder: 'content/library'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'library-post',
        }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Publiziert am', name: 'date', widget: 'datetime' }
      - { label: 'Beschreibung', name: 'description', widget: 'text' }
      - { label: 'Featured Post', name: 'featuredpost', widget: 'boolean' }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Landing Page'
        name: 'index'
        file: 'content/pages/index.md'
        fields:
          - label: 'Template key'
            name: 'templateKey'
            widget: 'hidden'
            default: 'landingPage'
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: text }
          - { label: Background Image, name: bgImage, widget: image }
          - { label: Me, name: meImage, widget: image }
          - label: Offering
            name: offering
            widget: object
            fields:
              - { label: Heading, name: heading, widget: string }
              - label: Offer Entries
                name: offers
                widget: list
                fields:
                  - { label: Heading, name: heading, widget: string }
                  - { label: Description, name: description, widget: text }
          - { label: Works Heading, name: worksHeading, widget: string }
          - label: Work Samples
            name: works
            widget: list
            fields:
              - { label: Image, name: img, widget: image }
              - { label: Caption, name: caption, widget: string }
              - { label: Description, name: description, widget: text }
          - label: Contact
            name: contact
            widget: object
            fields:
              - { label: Contact Heading, name: heading, widget: string }
              - { label: Contact Intro, name: intro, widget: text }
              - { label: Address Line 1, name: address01, widget: string }
              - { label: Address Line 2, name: address02, widget: string }
              - { label: Address Line 3, name: address03, widget: string }
              - { label: Phone, name: phone, widget: string }
              - { label: E-Mail, name: email, widget: string }
